[package]
name = "solid"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["serde_derive"] }
serde-xml-rs = "0.6.0"
serde_json = "1.0.107"
serde_yaml = "0.9.25"
